services:
  app:
    image: node:22-alpine
    container_name: synk_web
    ports:
      - ${PORT}:8080
    working_dir: /app
    volumes:
      - ./:/app
    env_file: .env
    command: sh -c "yarn && yarn dev"

    networks:
      - synk_network

networks:
  synk_network:
    external: true